version: '3'
services:
    db:
        image: mysql:latest
        container_name: test_sql
        cap_add:
            - SYS_NICE
        restart: always
        ports:
            -  '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: cpudata
        volumes:
            - db:/var/lib/mysql
            - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
    py_app:
        build: .
        container_name: py_app
        ports:
            - '5000:5000'
        volumes: 
            - ./app:/app
volumes:
    db:
        driver: local
